### ISSUE TITLE
241007 TODO

### ISSUE THREAD

**Issue by rlfrkdms1** [SeungAh-Yoo99/Hell-of-Algorithms#166]
## 필수
- [x] BOJ [23971](https://www.acmicpc.net/problem/23971)
- [x] BOJ [5073](https://www.acmicpc.net/problem/5073)
- [x] BOJ [2292](https://www.acmicpc.net/problem/2292)

### 여유가 난다면
- BOJ [1157](https://www.acmicpc.net/problem/1157)
