### ISSUE TITLE
241008 TODO

### ISSUE THREAD

**Issue by rlfrkdms1** [SeungAh-Yoo99/Hell-of-Algorithms#175]
## 필수
- [x] BOJ [1157](https://www.acmicpc.net/problem/1157)
- [ ] BOJ [2816](https://www.acmicpc.net/problem/2816)

### 여유가 난다면
- [ ] BOJ [11723](https://www.acmicpc.net/problem/11723)
