### ISSUE TITLE
241017 TODO

### ISSUE THREAD

**Issue by rlfrkdms1** [SeungAh-Yoo99/Hell-of-Algorithms#252]
### 필수
- [x] BOJ [20125](https://www.acmicpc.net/problem/20125)
- [x] BOJ [1205](https://www.acmicpc.net/problem/1205)

### 추가
- [x] BOJ [1244](https://www.acmicpc.net/problem/1244)
