### ISSUE TITLE
241022 TODO

### ISSUE THREAD

**Issue by rlfrkdms1** [SeungAh-Yoo99/Hell-of-Algorithms#287]
### 필수
- [x] BOJ [1515](https://www.acmicpc.net/problem/1515)
- [ ] BOJ [19941](https://www.acmicpc.net/problem/19941)
- [ ] BOJ [17484](https://www.acmicpc.net/problem/17484)
